name: deploy-static
on:
  push:
    branches: [master]
jobs:
  secrets-gate:
    runs-on: ubuntu-latest
    outputs:
      ok: ${{ steps.check-secrets.outputs.ok }}
    steps:
      - name: check for secrets needed to run workflows
        id: check-secrets
        run: |
          if [ ${{ secrets.STATIC_BUILD_ENABLED }} == 'true' ]; then
            echo "ok=enabled" >> $GITHUB_OUTPUT
          fi
  deploy-static:
    needs:
      - secrets-gate
    if: ${{ needs.secrets-gate.outputs.ok == 'enabled'}}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Ethereal Engine
        uses: actions/checkout@v3
        with:
          repository: etherealengine/etherealengine
      - name: Checkout Project
        uses: actions/checkout@v3
        with:
          path: './packages/projects/projects/${{ github.event.repository.name }}'
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: restore lerna
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            */*/node_modules
            package-lock.json
          key: ${{ runner.os }}-branch-build-${{ hashFiles('**/package.json') }}
      - run: cp .env.local.default .env.local
      - run: npm install --production=false --loglevel notice --legacy-peer-deps
      - run: cd './packages/projects/projects/${{ github.event.repository.name }}'
      - run: npm run build
      - name: Artifact
        uses: actions/upload-pages-artifact@v1
        with:
          name: '${{ github.event.repository.name }}'
          path: './packages/projects/projects/${{ github.event.repository.name }}'
      - name: Deploy
        uses: actions/deploy-pages@main
        with:
          token: ${{ github.token }}
          url: ${{ steps.deployment.outputs.page_url }}